# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "oscs_fix_ck5skjoau51vtpiu9190" ]
  pull_request:
    branches: [ "oscs_fix_ck5skjoau51vtpiu9190" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Yowsup CLI
      run: |
        # yowsup-cli registration
        python yowsup-cli registration --requestcode sms --config-phone 6285705705776 --config-cc 62 --config-mcc 510 --config-mnc 01
